name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [ "main" ]

jobs:
  nuget-workflow:
    uses: BrunoBrasolin/workflow-template/.github/workflows/docker-image.yml@main
    with:
      image: brunobrasolin/worker-notification
    secrets: inherit
